[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
shielded_pool = "NWRZDZJMfUAd3iVvdMhpsKht5bgHZGPzynHhQ2JssQ2"
vault_registry = "NWR5FUFsnn3x5gutivRDnBiFA6h1QZVVdAWM4PNdVEn"
zk_verifier = "NWRNe5ezj9SxCXVqrXbycbpT8drAvuaBknX3ChgGbnx"

[programs.localnet]
shielded_pool = "NWRZDZJMfUAd3iVvdMhpsKht5bgHZGPzynHhQ2JssQ2"
vault_registry = "NWR5FUFsnn3x5gutivRDnBiFA6h1QZVVdAWM4PNdVEn"
zk_verifier = "NWRNe5ezj9SxCXVqrXbycbpT8drAvuaBknX3ChgGbnx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[test.validator]
url = "http://127.0.0.1:8899"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[provider.localnet]
commitment = "confirmed"

[workspace]
members = [
    "programs/shielded-pool",
    "programs/zk-verifier",
    "programs/vault-registry",
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 60000 tests/**/*.ts"
