[package]
name = "vault-registry"
version = "0.1.0"
description = "NoirWire Vault Registry Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "vault_registry"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
# MagicBlock Ephemeral Rollups SDK for Permission Program CPI
ephemeral-rollups-sdk = { version = "0.8", features = ["access-control"] }

[dev-dependencies]
solana-program-test = "2.0"
